### ISSUE TITLE
Hillshade.py in ArcGIS Pro

### ISSUE THREAD

**Issue by jessevarner** [Esri/raster-functions#56]
I haven't been able to get the Hillshade function to work in ArcGIS Pro (2.2.0). I just get a blank image as a result, with no error message. Other functions do work as expected, such as AspectSlope.py. Has anyone else had success with Hillshade.py in Pro?

Note: I didn't install the separate Python extension packages, since the required scipy and numpy packages are already available in the ArcGIS Pro environment.

**Comment by jdrisdelle** [comment]
Thanks for pointing this out @jessevarner .  Not sure what is going on here. I just debugged into this and the output pixel block does have values in it. Looks like there is something funky going on with the pro display pipeline.  I also tried it in ArcMap and it is rendering properly.  Let me get back to you on this.

**Comment by jdrisdelle** [comment]
Hi @jessevarner .  We have a fix for this. There was a python 3 syntax issue in the utils.py file.  Thanks for reporting this. We will install the fix into Pro 2.3 . For now you can grab the version from here:

https://github.com/Esri/raster-functions/blob/pro23/functions/utils.py

I have create a new branch for Pro since this fix will break 10.x.  You can copy this file to 

`installdir\Program Files\ArcGIS\Pro\Resources\Raster\Functions\System`

You can also copy it to the local version of the python raster function that you cloned or downloaded.  Let me know if this works for you and we can close this issue.

**Comment by jessevarner** [comment]
This fix is working for me. Thank you very much for taking a look at this and fixing it so quickly!

**Comment by jdrisdelle** [comment]
Your welcome @jessevarner
